### ISSUE TITLE
Fails without package-lock.json

### ISSUE THREAD

**Issue by felixfbecker** [dependencies-io/actor-js-npm#25]
https://app.dependencies.io/projects/github/felixfbecker/vscode-php-intellisense/builds/18

```
rm: cannot remove '/repo/package-lock.json': No such file or directory
/usr/src/actor/node_modules/shelljs/src/common.js:417
      if (config.fatal) throw e;
                        ^

Error: exec: internal error
    at Object.error (/usr/src/actor/node_modules/shelljs/src/common.js:128:27)
    at Object._exec (/usr/src/actor/node_modules/shelljs/src/exec.js:292:12)
    at Object.exec (/usr/src/actor/node_modules/shelljs/src/common.js:350:23)
    at /usr/src/actor/entrypoint.js:101:11
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/usr/src/actor/entrypoint.js:22:14)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
```

**Comment by davegaeddert** [comment]
I didn't dig too deeply into this to figure out why `package-lock.json` did not exist...but it shouldn't be an error anymore.

**Comment by felixfbecker** [comment]
The project has an `.npmrc` that sets `package-lock=false` to always get the latest versions.

**Comment by felixfbecker** [comment]
Is this change deployed already? I still see the same error
https://app.dependencies.io/projects/github/felixfbecker/vscode-php-intellisense/builds/21

**Comment by davegaeddert** [comment]
Just deployed a minute ago, sorry I could have let you know it wasn't -- didn't think you'd try it so quickly!
