### ISSUE TITLE
Error: `panic: currently only works when there is exactly 1 dependency`

### ISSUE THREAD

**Issue by nathunsmitty** [dependencies-io/actor-js-npm#49]
Not sure if this is the right place to post this error, but I figured I'd try. Let me know if I should repost somewhere else!

I'm trying to set up denpendencies.io with a project (https://github.com/daily-bruin/sources) but I seem to be getting an error about an actor failing. This is what my [`dependencies.yml`](https://github.com/daily-bruin/sources/blob/master/dependencies.yml) file looks like:
```yml
collectors:

- type: js-npm
  path: /
  actors:
  - type: js-npm
    versions: "Y.Y.Y"
    settings:
      batch_mode: true
      related_pr_behavior: close
``` 

From going through the logs, the error I got was:
```

Successfully created https://github.com/daily-bruin/sources/pull/180
panic: currently only works when there is exactly 1 dependency

goroutine 1 [running]:
main.main()
	/home/travis/gopath/src/github.com/dependencies-io/pullrequest/cmd/pullrequest/main.go:49 +0x416
/usr/src/actor/node_modules/shelljs/src/common.js:401
      if (config.fatal) throw e;
                        ^

Error: exec: internal error
    at Object.error (/usr/src/actor/node_modules/shelljs/src/common.js:110:27)
    at Object._exec (/usr/src/actor/node_modules/shelljs/src/exec.js:206:12)
    at Object.exec (/usr/src/actor/node_modules/shelljs/src/common.js:335:23)
    at Object.<anonymous> (/usr/src/actor/entrypoint.js:141:9)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
```

Any ideas on what my problem is?

**Comment by davegaeddert** [comment]
Hey @nathunsmitty, looks like you've moved on to greenkeeper? In any case, our current implementation doesn't let you use `batch_mode: true` with `related_pr_behavior: close`. We're about to launch a major rework across the board though that will fix this and a number of other things -- hopefully in the next week or two.
